### ISSUE TITLE
GPL-697 New LH lab sample metadata & CT values (Randox) new files uploaded on 26th

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#138]
**User story**
GPL-697 | As Head of Service Delivery for Genomic Surveillance (Sonia G) I would like for Randox lab to be able to submit sample metadata including CT values to Sanger to onboard a new lighthouse lab

**Who are the primary contacts for this story**
Keith A (PAM)
Sonia G

**Acceptance criteria**
Basic new lab onboarding:
- [x] SFTP folder set up share name 'project-heron_randox'
- [ ] crawler processes files from that new folder
- [ ] sequencescape accepts plates with the correct barcode format ('URNxxxxx')
- [ ] baracoda creates COG UK IDs with the correct prefix ('RAND')

Adaptations to Randox files (TBD - currently asking if they are able to adapt their files to us):
- [ ] translate their column names into our standard column names
- [ ] translate Plate Well Number integer value into well position e.g. 'A01'
- [ ] create RNA ID value by concatenating Batch Name with above well position
- [ ] Make sure upper / lower case in Result field doesn't matter
- [ ] Check Date Tested format is consistent with others
- [ ] Allow 'Undetermined' value in CT result fields
- [ ] Allow 'E gene' value in CT target fields

**Comment by rl15** [comment]
NB expecting 5 boxes per week (80 plates per box, but may go down to 60) once a week = 5 * 80 * 96 = 37k

**Comment by rl15** [comment]
May have new RNA plate barcode format - TBD : https://ssg-confluence.internal.sanger.ac.uk/x/OpoKBg (see section 4.2.1)

**Comment by rl15** [comment]
PAM (Alan K) are setting up SFTP share with systems.

**Comment by rl15** [comment]
Expecting lab to be ready to go ~ 9th Nov

**Comment by rl15** [comment]
Potentially aim to have this in UAT by 2nd of December (floated estimate in 10am project meeting)

**Comment by rl15** [comment]
Randox prefix will be: TBD

**Comment by rl15** [comment]
Example file standard received 29th October
[Example template with CT Values - Sangers report.xlsx](https://github.com/sanger/crawler/files/5596196/Example.template.with.CT.Values.-.Sangers.report.xlsx)

**Comment by rl15** [comment]
Noted differences

1. File type / extension needs to be csv – example from 29th was xlsx
2. Batch name values to have well position concatenated eg AP-rna-00157141_A01
 -  If they can’t change this, currently well is separate column named ‘plate well number’, using 1-96 what is mapping B01 is 2 or 13?
3. Date tested to be as "2020-05-10 14:00:00 UTC" format
4. Col 3 change column name from ‘Batch name’ to ‘RNA ID’ if they can concatenate well positions
5. CT value change column names from
- Ch1Target, CH1 Result, Ch1Cq, Ch2Target, CH2 Result, Ch2Cq, Ch3Target, Ch3Result, Ch3Cq, Ch4Target, Ch4Result &  Ch4Cq to
- CH1-Target, CH1-Result, CH1-Cq, CH2-Target, CH2-Result, CH2-Cq, CH3-Target, CH3-Result, CH3-Cq, CH4-Target, CH4-Result & CH4-Cq
6. Col 1 change column name from ‘Sample’ to ‘Root sample ID’
7. Result value to match cases {Positive, Negative, Void} (not all Upper case)

**Comment by rl15** [comment]
SFTP share availble: project-heron_randox

**Comment by KatyTaylor** [comment]
On hold - waiting for reply from Randox lab about whether they can make their file format more similar to the other labs.
Started the crawler changes on this branch - https://github.com/sanger/crawler/compare/GPL-697-new-lh-lab-randox

**Comment by rl15** [comment]
Looking at SFTP now I can see 5 files uploaded 16:55 today. Files only have 2 channels in them Eg

Root Sample ID	
RNA ID	
Result	
Date Tested	
Lab ID	
CH1-Target	
CH1-Result	
CH1-Cq	
CH2-Target	
CH2-Result	
CH2-Cq

NB Files we were sent in October/November had all 4 channels

**Comment by rl15** [comment]
Alan K wrote (Tuesday, 19 January 2021 at 17:25)

Yes this is as expected, only 2 channels from Randox currently and they prefer sending individual files per box.

**Comment by KatyTaylor** [comment]
Looking at latest files sent to me by Rich:
lw-randox-biocentre-box-6-18820.csv
... up to ...
lw-randox-biocentre-box-15-18829.csv

They still have the following problems:
1. lw-randox-biocentre-box-6-18820.csv ... lw-randox-biocentre-box-6-18822.csv have columns 'URN' and 'Batch' instead of 'Root Sample ID' and 'RNA ID'

_Can we assume future files will be like the later ones in this batch and therefore have the correct column names?_

2. In those files that have 'RNA ID', the format of the coordinate at the end is D-9 rather than D09

_Shall we ask them to change this or code around it?_

**Comment by rl15** [comment]
Mistake by me is file standard from 19th that is what we expect. Current issues with files from 19th 


Current standard   headers | Randox headers from 19th | Comment on value
-- | -- | --
Root Sample ID | Root Sample ID | OK
Viral Prep   ID | MISSING: No longer rwquird so will change code sanger side
RNA ID | RNA ID | ISSUE: expecting 15JAN21-0034Q_B01 observed 15JAN21-0034Q_B-1 - curent   standrd has CNN
RNA-PCR ID | Result | OK
Result | Date Tested | OK
Date Tested | Lab ID | OK
Lab ID | CH1-Target | OK
CH1-Target | CH1-Result | OK
CH1-Result | CH1-Cq | OK
CH1-Cq | CH2-Target | OK
CH2-Target | CH2-Result | OK - Note new value
CH2-Result | CH2-Cq | OK
CH2-Cq |   | OK Expected to be absent
CH3-Target |   | OK Expected to be absent
CH3-Result |   | OK Expected to be absent
CH3-Cq |   | OK Expected to be absent
CH4-Target |   | OK Expected to be absent
CH4-Result |   | OK Expected to be absent
CH4-Cq |   | OK Expected to be absent

**Comment by rl15** [comment]
Files from 19th are the expected format


Current standard   headers | Randox headers from 19th | Comment on value
-- | -- | --
Root Sample ID | Root Sample ID | OK
Viral Prep   ID | MISSING: No longer rwquird so will change code sanger side
RNA ID | RNA ID | ISSUE: expecting 15JAN21-0034Q_B01 observed 15JAN21-0034Q_B-1 - curent   standrd has CNN
RNA-PCR ID |   | MISSING but not required
Result | Result | OK
Date Tested | Date Tested | OK
Lab ID | Lab ID | OK
CH1-Target | CH1-Target | OK
CH1-Result | CH1-Result | OK
CH1-Cq | CH1-Cq | OK
CH2-Target | CH2-Target | OK
CH2-Result | CH2-Result | OK - Note new value 'E-Gene'
CH2-Cq | CH2-Cq | OK
CH3-Target |   | OK Expected to be absent
CH3-Result |   | OK Expected to be absent
CH3-Cq |   | OK Expected to be absent
CH4-Target |   | OK Expected to be absent
CH4-Result |   | OK Expected to be absent
CH4-Cq |   | OK Expected to be absent

**Comment by rl15** [comment]
Randox have uploaded new files on 26th 

File names

lw-randox-biocentre-box-20-18834.csv
lw-randox-biocentre-box-19-18833.csv
lw-randox-biocentre-box-18-18832.csv
lw-randox-biocentre-box-17-18831.csv
lw-randox-biocentre-box-16-18830 - Copy.csv. (yes with the Copy suffix)

**Comment by rl15** [comment]
Header and first line from lw-randox-biocentre-box-16-18830 - Copy.csv looks like


Root Sample | AAI12345678
-- | --
RNA ID | 23JAN21-0830F_A10
Result | Positive
Date Tested | 2021-01-23 00:00:00 UTC
Lab ID | Randox
CH1-Target | ORF1ab
CH1-Result | Positive
CH1-Cq | 21.22
CH2-Target | E-Gene
CH2-Result | Positive
CH2-Cq | 22.28

**Comment by rl15** [comment]
Katy commented in Slack

Found following issues:

1. “Root Sample” not “Root Sample ID”
2. Has a Byte Order Mark (BOM)
3. Doesn’t have RNA-PCR ID
4. Doesn’t have Viral Prep ID

Coding round

**Comment by KatyTaylor** [comment]
Something to watch out for:

A few rows failed validation in lw-randox-biocentre-box-19-18833.csv because the coordinate in the RNA ID field was formatted wrongly (e.g. lines 296 and 297)

Incorrect: B011
Correct: B11

Only single digits should be pre-padded with a 0 (e.g. C01 is correct)

**Comment by rl15** [comment]
Confirmed seeing Randox samples in +ves report and MLWH from 4th
In stand up on 4th Rich C confirmed Operations will be picking from box 21 inclusive.
