### ISSUE TITLE
GPL-771 Migrate all samples to use the new filtered_positive fields

### ISSUE THREAD

**Issue by Chris-Friend** [sanger/crawler#167]
**User story**
In migrating to Beckman, we have added new filtered_positive fields to samples. These simplify the existing "fit to pick" rules distributed throughout various codebases/queries. As such, and **before any fit to pick rule changes**, we should migrate all old samples to include `filtered_positive` values in both Mongo and MLWH, and update any queries to simply check the value of the `filtered_positive` field.

This will also mean we only have to change the fit to pick rules in one place: crawler, where the fields are first set on inserting/updating samples.

**Who are the primary contacts for this story**
Katy T
Eduardo M
Phil
Chris F

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Migrate all samples as per the "Migration to apply pickable decision (crawler)" in [this diagram](https://lucid.app/lucidchart/25bd99ee-1fbf-4706-a7dc-974c17b4ac7b/edit?shared=true&page=0_0#?folder_id=home&browser=icon): get all samples from mongo -> apply the filtered positive rules in crawler to them -> update mongo -> update MLWH. It may be possible to do this by simplifying the crawler migration implemented as part of GPL-733.
- ~~Change the `STAGE_MATCH_POSITIVE` and `POSITIVE_SAMPLES_MONGODB_FILTER` to use the new `filtered_positive` field: a sample is fit to pick if this is `True`~~ See https://github.com/sanger/General-Backlog-Items/issues/80
- ~~Update any queries used by/sent to PaM to instead use the new `filtered_positive` field~~ See https://github.com/sanger/General-Backlog-Items/issues/81

**Additional context**

**Comment by rl15** [comment]
From March 2020 to 17th Dec migration = 17H
