### ISSUE TITLE
GPL-819 The crawler can put plate barcodes into the MLWH lighthouse_sample table which contain spurious white space 

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/crawler#214]
**Describe the bug**
The crawler can put plate barcodes into the MLWH lighthouse_sample table which contain spurious white space.

Only 25 plate barcode currently have tailing whitespace in the MLWH, which is not many out of 23.3 million rows....

**RT Ticket Number**
N/A

**To Reproduce**
Suggested steps to reproduce the behaviour in test:
1. Ask crawler to process a file containing plate barcodes with preceding or trailing spaces (see examples below)
2. Observe lighthouse_sample table being populated with these

**Expected behaviour**
I would expect these barcodes to be detected by the crawler and either logged as an error and/or trimmed to remove the spaces.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**

Problem plate barcodes currently in the lighthouse_sample table listed below, generated from

`SELECT DISTINCT plate_barcode FROM lighthouse_sample WHERE  INSTR(plate_barcode, ' ') > 0;`

" RNA008583"
" AP-rna-00115445"
" RNA020797"
"AP-rna-00026995 "
"GLA008074R "
"GLA008028R "
" 002127987"
"GLA010285R "
"AP-rna-00128103 "
" GLA019321R"
" GLA019716R"
" GLA019715R"
" GLA019659R"
" GLA019717R"
" GLA019650R"
" GLA019651R"
"AP-rna-00142151  "
" AP-rna-00145460"
"AP-rna-00146061 "
"AP-rna-00130886 "
"AP-rna-00148159 "
"RNA427769 "
" AP-rna-00152533-rna-00152877"
"AP-rna-00190145 "
"RNA459749 "

**Comment by andrewsparkes** [comment]
Code fix already done by Phil over a month ago, to trim whitespace and other spurious characters. Examples above appear to be older, from late summer. Checking with Tom whether data needs fixing.

**Comment by andrewsparkes** [comment]
Confirmed last seen instance was 14th Dec, code fix was implemented 16th December.
Confirmed data does NOT required fixing, as already used in current form in PAM reports and would cause further confusion.
