### ISSUE TITLE
GPL-861 Plate map changes to support consolidated plates from Hamilton CP [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#261]
**User story**
GPL-861 | As LIMS team we need to refine the plate map standard to support a change directed by consolidating plates and new robotics

**Who are the primary contacts for this story**
Sonia G (PAM)
Cristina A (PAM)
Alan K (PAM)

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] New gene `RNaseP` & `IEC` for 'CHn-Target' (n in 1..4)
- [x] Parse `Empty` in addition to no value for 'Root Sample ID'; do not log, ignore any other row data 
- [x] Parse `Unknown` for CT values (same as empty cell)
- [x] Parse consolidated plate map files with file name format described in additional context
- [ ] Lighthouse plate map standard document is updated to reflect changes
- [ ] change required in lighthouse service for sentinel process - if the lab ids are different for a plate it will fail
- [x] Ignore `PickResult` column and not log the error

**Additional context**

Lighthouse | Surveillance Barcodes Format | Surveillance Barcodes Example | Eagle Barcode Format | Eagle Barcode Example
-- | -- | -- | -- | --
Milton Keynes | XXXNNNNNN | RNA123456 | XXXNNNNNN | EGL123456
Alderley Park | XX-XXX-NNNNNNNN | AP-rna-12345678 | XXXNNNNNN | APE123456
Glasgow | XXXNNNNNNX | GLA123456R | XXXNNNNNN | EGG123456<br>GLS123456
Cambridge | NNNNNNNNN | 123456789 | XXXNNNNNN | EGC123456<br>CBE123456
Randox | XXX-AA-NNNNNNNN | RDX-J1-123456 | XXXNNNNNN | RXE123456

- X: Letter Character (Upper or Lower case)
- A: Alphanumeric Character (Upper or Lower case)
- N: Number

__NB__
Current state play: If the coordinate is put in a separate column rather than concatenated to the plate id, the row will fail.

Dan L Wrote (26 February 2021 12:03)
> Thanks for confirming point 1, 

and example file received on 26th Feb has well position e.g.: `AP-rna-00195161_A01`

**Uncertainty**
- From feedback on the 11th February from Dan J L (Deloitte) have remaining uncertainty to clarify.
- Result ‘Limit of detection’ may change.
- > It would be extremely helpful if the Sanger can let me know the characters allowed for the filename – like A-Z, a-z, 0-9, and the special characters allowed, it would give us some flexibility while still able to support Sanger requirements.

  Assume we would need list of special characters to add this to regex.

- There is the as yet untested idea that special characters would be handled well by the SFTP sever itself.

**Comment by rl15** [comment]
Alan K wrote (Tuesday, 16 February 2021 at 12:15)
This will be required once LHs shift to cp on site. Timeline for this is unknown but could be within the month

Q> Can we  assume all the LH labs wil use the new file naming convention? - PSG
                
A. All LHs using Hamiltons will use this format (AP/MK/GLS) but hope that Randox and CAM will also align.

**Comment by rl15** [comment]
Alan K wrote(Thursday, 18 February 2021 at 10:18)

Q> Do you want us to prioritise this change?

Go-live looks like late next week at earliest. Is that a feasible timeline for you and the team? Understand things are manic currently so let me know.
 
Q> I assume all the LH labs will use the new file naming convention?

As I said before all LHs using Hamiltons will use this format (AP/MK/GLS). No current direction from Deloitte for other labs but will see if Randox and CAM will also align.

**Comment by rl15** [comment]
Alan K wrote (Friday, 19 February 2021 at 14:23)

“One potential result of the testing (in simulation) is changing the naming convention of the output plates. I originally proposed the <purpose><barcodeID>.csv schema so LHLs can easily identify where to send each plate map. Yesterday we find out it may interfere with Hamilton’s logic to avoid accidental double picking into the same plate, so we may simplify the plate map filename to <barcodeID>.csv only and save different files into different sub-folders. Hence, would be great if Sanger can make the change to accommodate <barcodeID>.csv format in future as well.”

**Comment by rl15** [comment]
Dan L (deloitte) wrote (26 February 2021 12:03)

[20210226_example_plate_maps.zip](https://github.com/sanger/crawler/files/6050745/20210226_example_plate_maps.zip)

Please find attached two example output files from AP (we used mock input plate maps for the testing that’s why lab IDs are GLS and CB). The filename is in line with general AP RNA plates – note this is only for general surveillance plates. For priority plates, per discussed on the earlier call, CB will print barcodes starting with EAP prefix and send to AP.

**Comment by pjvv** [comment]
@rl15, Is the new gene ICE or IEC?

**Comment by pjvv** [comment]
@rl15 
> Parse “Unknown” for CT values (Same as empty cell)

Is that for all CT columns? Target, Result and Cq? Or just one of them?

**Comment by andrewsparkes** [comment]
@rl15
Is the PickResult column **required** for consolidated files?
Should it be stored in MongoDB and MLWH?
I suspect it indicates whether the cherrypick happened, to transfer the sample to the consolidated plate (Hamilton robots have liquid sensing). If so it should be used in the positive filtering rules (no point us trying to sequence something that wasn't transferred into the plate).
Also what are the allowed values, we currently see '**Success**' and '**Insufficient volume**' in the example files.

**Comment by neilsycamore** [comment]
@rl15 Alan K via RT 713867 added 2 more Eagle prefix

Lab | Prefix
AP | APE
Randox | RXE

**Comment by andrewsparkes** [comment]
@rl15
So we have different orders of letters for the Eagle prefixes? EAP, APE, RXE, CBE, EMK? Be easier to follow if they were 'E' first then the lighthouse letters, or at least consistant...

**Comment by pjvv** [comment]
From: Alan K
Sent: 02 March 2021 14:04
To: Rich Livett
Subject: RE: AP cherry picking pre go-live alignment [EXT]
 
> Thanks Rich
Corrections below:
>
> Purpose is now no longer being used as a prefix so plate barcode will be the file name. Any accepted plate barcodes will need to be accepted as file name standards. Suggest start with Eagle varieties (XXXnnnnnn) and AP (for example AP-rna-00223715)
>
> Lab | Prefix
> -- | --
> CB | CBE
> GLA | GLS
> MK | EMK
> AP | APE
> Randox | RXE
>

**Comment by pjvv** [comment]
From: Alan K
Date: Wednesday, 3 March 2021 at 11:59
To: Richard Livett
Subject: RE: AP cherry picking pre go-live alignment [EXT]
 
> Further update:
>
> Randox now using plate barcode as file name as of 03/03.
>  
> Eg. RDX-J2-020035

**Comment by pjvv** [comment]
@rl15 I can't see an example of `RNaseP`, where is that coming from?

**Comment by pjvv** [comment]
From: Alan K
Date: Wednesday, 10 March 2021 at 10:36

Lighthouse | Surveillance Barcodes Format | Surveillance Barcodes Example | Eagle Barcode Format | Eagle Barcode Example
-- | -- | -- | -- | --
Milton Keynes | XXXNNNNNN | RNA123456 | XXXNNNNNN | EGL123456
Alderley Park | XX-XXX-NNNNNNNN | AP-rna-12345678 | XXXNNNNNN | APE123456
Glasgow | XXXNNNNNNXXXX-AA-NNNNNNNN | GLA123456R?? | XXXNNNNNN | EGG123456GLS123456
Cambridge | NNNNNNNNN | 123456789 | XXXNNNNNN | EGC123456CBE123456
Randox | XXX-AA-NNNNNNNN | RDX-J1-123456 | XXXNNNNNN | RXE123456

**Comment by pjvv** [comment]
From: Alan K
Date: Mon, 15 Mar 2021 12:45:17 

Lighthouse | Surveillance Barcodes Format | Surveillance Barcodes Example | Eagle Barcode Format | Eagle Barcode Example
-- | -- | -- | -- | --
Milton Keynes | XXXNNNNNN | RNA123456 | XXXNNNNNN | EGL123456
Alderley Park | XX-XXX-NNNNNNNN | AP-rna-12345678 | XXXNNNNNN | APE123456
Glasgow | XXXNNNNNNX | GLA123456R | XXXNNNNNN | EGG123456GLS123456
Cambridge | NNNNNNNNN | 123456789 | XXXNNNNNN | EGC123456CBE123456
Randox | XXX-AA-NNNNNNNN | RDX-J1-123456 | XXXNNNNNN | RXE123456
