### ISSUE TITLE
GPL-930 Housekeeping - Legacy data with plate barcodes and rna_id with trailing whitespaces

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#276]
**Describe the Housekeeping**
We have some samples from last year where the rna_id and plate barcode are starting with a whitespace:
``
select * from lighthouse_sample where rna_id like ' %' 
```
We would like to update the databases that have this legacy data:

[ ] Mongodb
[ ] mlwh
[ ] dart

**Blocking issues**
Describe any other issues or tickets that may be blocking this change.

**Additional context**

Mail on March 8th, 16:30

**Comment by KatyTaylor** [comment]
Dealt with as part of https://github.com/sanger/crawler/issues/267
