### ISSUE TITLE
GPL-937 BUG - duplicate detection with same testing date not matching (C=S , V=2)

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#289]
**Describe the bug**
When same data for a sample is uploaded and same testing date, it triggers an error as if the testing date were different, which is confusing. It should log an error as a normal sample duplicate (not different testing date), not an error with different testing date.

```
WARNING: Samples rows matching previously uploaded rows but with different test date. (TYPE 7) (e.g. Already in database, line: 2, root sample id: xxxx, dates: (2021-03-18 16:02:45 != 2021-03-18 16:02:45+00:00)) (e.g. Already in database, line: 3, root sample id:
```

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by TWJW-SANGER** [comment]
I believe this is no longer relevant following the handover to GSU.
