### ISSUE TITLE
GPL-925-1 Further RNA plate barcode & plate map file name formats required by 2nd April [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#295]
**User story**
GPL-925 | As representative for LH labs (Alan K) I would like to accept covid samples from MK, Glasgow and AP that have further plate barcode changes by 2nd April

**Who are the primary contacts for this story**
Alan K (PAM)

**Acceptance criteria**
To be considered successful the solution must allow:

For MK
- [x] RNA CP plate barcode for MK: cpRNANNNNNN eg cpRNA123456
- [x] With corresponding change to the plate map filename, cpRNA123456.csv
- [x] RNA Eagle plate barcode for MK:  EMKNNNNNN eg EMK123456 (NB may have been changed previously)

For AP:
- [x] RNA CP plate barcode for AP: XX-XXX-NNNNNNNN eg AP-chp-12345678
- [x] With corresponding change to the plate map filename, AP-chp-12345678.csv

For Glasgow:
- [x] RNA CP plate barcode for Glasgow: GLS-GP-NNNNNN eg GLS-GP-123456
- [x] With corresponding change to the plate map filename, GLS-GP-123456.csv

New barcode formats added to SS, class with regex, valid foreign barcodes (for Sentinel only directly in SS)
Updates to accepted file names in Crawler

 
**Dependencies**

**Additional context**
Alan K wrote (Tuesday, 23 March 2021 at 12:19)

...
We have just been made aware of some further change being implemented at the Lighthouses. I’ve copied updated tables for file names and barcode formats below and highlighted the changes. **Note: feel free to ignore Brant’s Bridge** in this request as I’ll need to send all new LH data through. I thought I’d include in case it is easier to do these items as batches.
...

Lighthouse | Unconsolidated plate barcode format | Unconsolidated plate barcode example | CP plate barcode format | CP plate barcode example | Eagle Barcode Format | Eagle Barcode Example
-- | -- | -- | -- | -- | -- | --
Milton Keynes | XXXNNNNNN | RNA123456 | cpRNANNNNNN | cpRNA123456 | XXXNNNNNN | EMK123456
Alderley Park | XX-XXX-NNNNNNNN | AP-rna-12345678 | XX-XXX-NNNNNNNN | AP-rna-00210235, AP-chp-12345678 | XXXNNNNNN | APE123456
Glasgow | XXXNNNNNNX | GLA123456R | GLS-GP-NNNNNN | GLS-GP-123456 | XXXNNNNNN | EGG123456GLS123456
Cambridge | NNNNNNNNN | 123456789 | NNNNNNNNN | 002220450 | XXXNNNNNN | EGC123456CBE123456
Randox | XXX-AA-NNNNNNNN | RDX-J1-123456 | XXX-AA-NNNNNNNN | RDX-J1-123456 | XXXNNNNNN | RXE123456
Brant's Bridge | NNNNNNNNNNNNNNNNN | 95040456000420484 |   |   |   |  

Lighthouse | Surveillance Plate Map file names | Eagle Plate Map file names | Unconsolidated Plate map file names
-- | -- | -- | --
Milton Keynes | RNA123456, cpRNA123456 | EGL123456 | MK_sanger_report_210315_0800
Alderley Park | AP-rna-12345678, AP-chp-12345678 | APE123456 | AP_sanger_report_210315_0130
Glasgow | GLA123456R, GLS-GP-123456 | EGG123456GLS123456 | GLS_sanger_report_210315_0500
Cambridge | 123456789 | EGC123456CBE123456 | CB_sanger_report_210315_0126
Randox | RDX-J1-123456 | RXE123456 | lw-randox-box-55-18869
Brant's Bridge |   |   |

**Comment by harrietc52** [comment]
Coupled with SS story [GPL-925-2](https://github.com/sanger/sequencescape/issues/3136)
