### ISSUE TITLE
GPL-985-1 Automated processing on Beckmans: Health Services Laboratories (HSL) 

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#316]
**User story**

GPL-985 | AS representative for LH labs (Alan K) I would like automated processing of surge testing samples from Health Services Laboratories (HSL) (London) to deprecated troublesome Eagle process
-- | --

**Who are the primary contacts for this story**
Alan K (PAM)
Sonia G (PAM)
Rich C (ops)
James M (ops)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Plate maps standard distributed by Alan to HSL lab lead: https://docs.google.com/document/d/1XC1pwqVTF2uLfyXWzth_cKd-f3B3g1Px8VoauuZ6RW4/edit?usp=sharing
- [ ] Enable read from SFTP share `project-heron_hsl` (Share is there from 19th April) (check LIMS have read access)
- [ ] Need lab_id: HSLL
- [ ] biomek_labware_class: `BIOMEK_LABWARE_CLASS_KINGFISHER` ?? 

**Additional context**

**Comment by harrietc52** [comment]
support HSL barcodes in Sequencescape for automatic creation through lighthouse workflows (Sentinel and Beckman) The new barcode format to support is: HSLnnnnnn (e.g. HSL123456)

Confirm below values
```
    {
        "barcode_field": FIELD_RNA_ID,
        "barcode_regex": CENTRE_REGEX_BARCODE,
        "name": "Health Services Laboratories",
        "prefix": "HSL",
        "lab_id_default": "HSL",
        "backups_folder": f"{CENTRE_DIR_BACKUPS}/HSL",
        "sftp_file_regex_unconsolidated_surveillance": f"",
        "sftp_file_regex_consolidated_surveillance": r"^",
        "sftp_file_regex_consolidated_eagle": r"",
        "sftp_root_read": "",
        "file_names_to_ignore": [],
        "biomek_labware_class": BIOMEK_LABWARE_CLASS_KINGFISHER,
    },
```

This story is related with story: sanger/baracoda#111
This story is coupled with SS https://github.com/sanger/sequencescape/issues/3164

**Comment by harrietc52** [comment]
Answer from Ian K.
1.       Yes plan is to have these uploaded to the SFTP with the file name to be that of the plate ID. So “HSLnnnnnn.csv”.
2.      Is lab ID distinct from COG UK ID? We are using “HSLL” as COG-UK ID so seems sensible to keep aligned.
3.      Will be uploaded to a new folder in the SFTP: /project-heron_hsl

Will need to format this into acceptance criteria for the story.

**Comment by rl15** [comment]
Expecting to prioritize item for week commencing 3rd May. (From DT4/DT6 meeting discussion)~ 2 weeks of running went live on 20th

**Comment by harrietc52** [comment]
Deployed to UAT on 27.04.21
Error becuase `project-heron_hsl`, which is the sftp_root_read, doesnt exist in the SFTP
Redeployed previous version: 1.12.1-develop at 14:15

**Comment by rl15** [comment]
Incident Incident [.297620] creted to get read access: User psd-lims does not have read permission to sftpsrv.sanger.ac.uk/project-heron_hsl

**Comment by rl15** [comment]
Incident Incident [.297620] closed - confirmed working
