### ISSUE TITLE
GPL-983-03 Support new barcode format HSLnnnnnn

### ISSUE THREAD

**Issue by harrietc52** [sanger/crawler#320]
**User story**
As PAM, I want to support HSL barcodes in Sequencescape for automatic creation through lighthouse workflows (Sentinel and Beckman)
The new barcode format to support is: HSLnnnnnn (e.g. HSL123456)

Original story [GPL-983](https://github.com/sanger/baracoda/issues/111)

**Who are the primary contacts for this story**
Alan K.

**Acceptance criteria**
Confirm below values
```
    {
        "barcode_field": FIELD_RNA_ID,
        "barcode_regex": CENTRE_REGEX_BARCODE,
        "name": "Health Services Laboratories",
        "prefix": "HSL",
        "lab_id_default": "HSL",
        "backups_folder": f"{CENTRE_DIR_BACKUPS}/HSL",
        "sftp_file_regex_unconsolidated_surveillance": f"",
        "sftp_file_regex_consolidated_surveillance": r"^",
        "sftp_file_regex_consolidated_eagle": r"",
        "sftp_root_read": "",
        "file_names_to_ignore": [],
        "biomek_labware_class": BIOMEK_LABWARE_CLASS_KINGFISHER,
    },
```

**Dependencies**
This story is related with story: sanger/baracoda#111
This story is coupled with SS https://github.com/sanger/sequencescape/issues/3164

**Additional context**

**Comment by emrojo** [comment]
Answer from Ian K.
1.       Yes plan is to have these uploaded to the SFTP with the file name to be that of the plate ID. So “HSLnnnnnn.csv”.
2.      Is lab ID distinct from COG UK ID? We are using “HSLL” as COG-UK ID so seems sensible to keep aligned.
3.      Will be uploaded to a new folder in the SFTP: /project-heron_hsl

Will need to format this into acceptance criteria for the story.

**Comment by harrietc52** [comment]
Closing as Issue has been moved to [GPL-985 ](https://github.com/sanger/crawler/issues/316)
