### ISSUE TITLE
GPL-995 Automated processing on Beckmans: New LH lab Plymouth (PLYM) [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#328]
**User story**
As representative for LH labs (Alan K) I would like to begin receiving COVID samples from a new LH lab - Plymouth (PLYM) - to support automated picking on robotics 

**Who are the primary contacts for this story**
Alan K (PAM)
Sonia G (PAM)
Critina A (PAM)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Plate maps [standard](https://docs.google.com/document/d/1XC1pwqVTF2uLfyXWzth_cKd-f3B3g1Px8VoauuZ6RW4/edit?usp=sharing) distributed by Alan to PLYM lab lead 
- [ ] Expected file name (all plates on one): `SW_sanger_report_000000_0000.csv`
- [ ] Expected file name (individual files per plate): `PLY-chp-123456.csv`
- [x] Enable read from SFTP share `project-heron_plym` (Share is there, `psd-lims` has read access)
- [ ] Create `lab_id`: `PLYM`
- [ ] Support creating a plate with barcode `PLY-chp-123456` in Sequencescape
- [ ] New COG-UK prefix: `PLYM`
- [ ] `biomek_labware_class`: kingfisher DWP

**Comment by rl15** [comment]
Alan K wrote (Wednesday, 28 April 2021 at 16:06) 
PLYM are nearing go-live and I can see end of next week as a potential date.

**Comment by rl15** [comment]
Alan K wrote (Thursday, 29 April 2021 at 11:45)

Single file uploaded previously as a test. They plan to do a full run today/tomorrow to test automated upload so will be a new file tomorrow if the current one is not acceptable (it’s a few weeks old now).

**Comment by rl15** [comment]
Alan K wrote (Wednesday, 5 May 2021 at 17:22) 

PLYM plan to upload plate map test tonight at some point so it should be there for the team for validation anytime from tomorrow.

**Comment by emrojo** [comment]
The filename received "SW_sanger_report_210406 1126.csv" contains a whitespace, but it should be underscore instead (SW_sanger_report_210406_1126.csv)

**Comment by pjvv** [comment]
Re. the `biomek_labware_class`, we currently use `KingFisher_96_2ml`, is `kingfisher DWP` the same or a typo or something different?
