### ISSUE TITLE
DPL-014 - Back load DART database to CP 'Fit to pick' samples prior to December 2020

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#345]
**User story**
DPL-014 | As a operational lead for PAM (Sonia G) I want to be able to pick covid samples prior to December on Beckman robotics for Training and surveillance understanding/research interest to help understand the spread of the pandemic in the early days.

**Who are the primary contacts for this story**
Sonia G (PAM)
Cristina A (PAM)
Tanya B
Lesley S (RnD)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Run the migration scripts in UAT first (has been 5 month since work was complete)
- [ ] Backdate load from 12/04/20 and 09/06/20 for date tested  (Mail Cristina A on Tuesday, 18 May 2021 at 10:40) 
- [ ] 134 plates of interest have been identified from early in the pandemic, these are still onsite and set aside by Bart’s team) - see attachment below 
- [ ] Understand impact on reporting (communication to PAM on whats changing in operations)

**Additional context**

- Raised in standup on 14th May
- Ian’s aim is to run the first test by mid-June.
- Considerations for Processing Archived Lighthouse Plates - Google Docs
- **https://docs.google.com/document/d/1Wkrpq2Bs8kxEEq7ICTG3eIWwzqFBtsA23i4JNUXNRcc/edit?ts=609154d9**

Rich L was wrong really did not expect to do this - trust the judgment of the team.

**Comment by rl15** [comment]
[Uploading Historical samples.csv…]()

**Comment by rl15** [comment]
[Historical samples.csv](https://github.com/sanger/crawler/files/6502692/Historical.samples.csv)

**Comment by TWJW-SANGER** [comment]
Considered for deprecation as the older samples will be run on Biosero robots with the RVI project now which does not use the DART database.

**Comment by TWJW-SANGER** [comment]
Deprecated by the Product Owner.
