### ISSUE TITLE
DPL-025 Automated processing on Beckmans: New LH lab Leamington Spa (LSPA) [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#349]
**User story**
DPL-025 | As representative fo LH labs (Alan K) I would like to begin receiving covid samples from new LH lab; Leamington Spa (LSPA) to support automated picking on robotics

**Who are the primary contacts for this story**
Alan K (PAM)
Sonia G (PAM)
Cristina A (PAM)

**Acceptance criteria**
To be considered successful the solution must allow:

- [x] Plate maps standard distributed by Alan to LSPA lab lead
- [ ] Expected file name (individual files per plate): LML_CHERY123567.csv
- [ ] Enable read from SFTP share /project-heron_lspa (Share is there, not checked psd-lims has read access)
- [ ] Create lab_id: LML
- [ ] Support creating a plate with barcode CHERYnnnnnn, eg CHERY500171 in Sequencescape 
- [ ] New COG-UK prefix: LSPA
- [ ] biomek_labware_class: kingfisher DWP (confirmed 27th May AK)

**Assumptions**

1. - No unconsolidated plate map file type expected
2. - Ct values will not be received as this is ePCR (AK 7/7/21)

**Additional context**
Change: Expected on line earlier rather than late June.

**Comment by rl15** [comment]
> Alan K wrote (Thursday, 27 May 2021 at 10:13)

> Timeline looks like 17/06 for first tests in LSPA – at that point they are requesting we receive unconsolidated plates for a minimum of 3 weeks before they can implement cherry picking. (n.b We still need to get approval for the receipt of unconsolidated plates).

**Comment by rl15** [comment]
> Alan K wrote (Wednesday, 7 July 2021 at 16:31)

> we have managed to convince LSPA to make the change to the file sent though so expect “Positive” in the new results file to be uploaded today (or emailed if that’s what comes through first).  request to receive “Detected” as “Positive” now obsolete.
 
> Negatives will not be picked but should the occurrence appear they will be “Negative” as stated in our standards doc.

**Comment by KatyTaylor** [comment]
Deployed crawler, baracoda and sequencescape changes to UAT today. First run picked up test plates LML_CHERY00000014 and LML_CHERY00000015 from the sftp, and they processed fine (inserted into MongoDB, lighthouse_sample and DART). Tested importing LML_CHERY00000014 into Sequencescape using Sentinel, and it went in fine and got assigned a correct COG UK ID.
