### ISSUE TITLE
DPL-087 - As a Genomic Surveillance Officer (AK) I would like a new validation rule applied to plate maps such samples with a date tested in the future raise an error

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/crawler#350]
**User story**
As a Genomic Surveillance Officer (AK) I would like a new validation rule applied to plate maps such samples with a date tested in the future raise an error.

**Who are the primary contacts for this story**
AK
CA
SG

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] samples with a date tested in the future should raise an error visible to SSR's
- [ ] samples with a date tested in the future do not continue in the process

**Dependencies**

References

**Additional context**
The errors will be fed back to the Lighthouse lab responsible and they must resubmit the plate map.
This error has happened because of manual editing in the Lighthouse lab, with new labs coming online we'd like to avoid this happening again.

**Comment by rl15** [comment]
Creates failure demand

**Comment by TWJW-SANGER** [comment]
This is covered by Heron - OKR transfer - deprecating.

The whole plate is rejected with explicit reasons if one sample is invalid. Sample creation and update errors will be shown in lighthouse-ui.
