### ISSUE TITLE
DPL-029 - Make lab_id a mandatory field

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/crawler#355]
**User story**
As anyone invested in the Heron project, I would like to make lab_id a mandatory field, because otherwise this happens:
1. file has blank lab_ids
2. if ADD_LAB_ID config flag is false, no default value is set and lab_id is blank in mongo / lighthouse_sample
3. lab_id is blank in DART
4. create destination plates endpoint (end of Beckman run) queries from DART and doesn't retrieve any samples where lab_id is null
5. No errors, plate gets created in Sequencescape but missing samples

**Who are the primary contacts for this story**
Katy, Phil, Andrew, Eduardo

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] If a file has rows where lab_id is blank, those rows should be rejected
- [ ] Remove the 'ADD_LAB_ID' behaviour, as it will conflict with this

**Additional context**
This got picked up when Phil and Katy tried to crowbar the 3 special MK plates through the crawler.
Some lab_ids in the file were set to 'N/A' so we set them to blank, expecting the defaults to kick in and populate them with 'MK', but it didn't so they stayed blank.
This is because the flag 'ADD_LAB_ID' was set to false, and the row does not error when lab_id is blank.
From Eduardo in Slack: "seems originally that was a TYPE 2 error in crawler / but now TYPE 2 only check Root Sample ID, RNA ID and Result"
At time of writing, there were no lighthouse_sample rows with blank lab_id, so the files must consistently have this field filled in.

**Comment by TWJW-SANGER** [comment]
Resolved as part of GSU taking over SFTP file processing.
Deprecated by the Product Owner.
