### ISSUE TITLE
DPL-034 UAT Action - Setup Cherrypick Test Data - Crawler elements [Heron]

### ISSUE THREAD

**Issue by harrietc52** [sanger/crawler#356]
**User story**
As PSD we would like an easier way to create cherrypicking test data (source plate data) in the UAT environment. The goal is to have an interactive screen in Lighthouse UI where you select the quantity of plates and numbers of fit to pick samples in them and it triggers the generation of a test data setup via Lighthouse and Crawler.
This story tracks the Crawler elements of this process.

**Who are the primary contacts for this story**
Andrew
Phil
Harriet
Eduardo

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Add Flask to Crawler with simple API
- [x] Create a POST endpoint to trigger generation of test data, passing the run ID in the body
- [x] Cherrypick Test Data Generation is wrapped in a State Machine
- [x] API endpoint updates test run status in the Mongo collection to 'Started'
- On "Started" state: 
- [x] API endpoint fetches plate information from Mongo collection by run id. 
- [x] API endpoint Calls method to generate data for the specified set of plates
- [x] API endpoint updates test run state in the Mongo collection to 'GeneratedPlateData'
- On "GeneratedPlateData" state:
- [x] API endpoint calls method to write to a Lighthouse csv file and put it into the sftp-data directory in the docker container (under a fake lighthouse directory called CPTD for Cherry Picker Test Data)
- [x] API endpoint updates test run state in the Mongo collection to 'CreatedFile'
- On "CreatedFile" state:
- [x] API endpoint then calls the standard crawler method, specifically targeting the CPTD centre, to parse any outstanding file(s) into the databases
- [x] API endpoint updates test run state in the Mongo collection to 'Completed'
- [x] API endpoint updates test run state in the Mongo collection to 'Failed' if any problem
- [x] A list of plate barcodes and description text are added to the Mongo collection for barcode printing
- [x] API endpoint returns a summary JSON object after all the above has happened.  This will either be a summary of what was created, or a list of errors

**Dependencies**
This story is being done in parallel with these stories:
https://github.com/sanger/lighthouse-ui/issues/73
https://github.com/sanger/lighthouse/issues/322

**Additional context**
LucidChart diagram [here](https://lucid.app/lucidchart/invitations/accept/inv_1b8208a2-17e8-498d-a301-bf34b64f3c6d) showing Lighthouse UI mock ups and UAT Action process

**Comment by sdjmchattie** [comment]
I've fully implemented this, but I'm working on the unit tests before it gets reviewed
