### ISSUE TITLE
DPL-042 | Research: Understand changes required to move 'fit to pick logic' from core informatics to GSU [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#362]
**Description**
DPL-042 | Research: Understand changes required to move 'fit to pick logic' from core informatics to GSU

**Who the primary contacts are for this work**
Callum S (GSU)
Rhys (GSU)
Rich L 

**End point**

- Allow PAM (via API) to direct which samples to pick on Beckmans or Biosero Hamiltons

**Assumptions**

- Pick set as a boolean value on PSG (The details of why should be picked are not know to PSD services, it maybe the case that positive samples will not be picked as there are other positives to pick that have a high scientific value to sequence) 
- In first iteration its understood plates that have samples that must be picked will still be preferentially selected by operation using Box buster.

**Context**
Overview of existing service here: https://lucid.app/lucidchart/invitations/accept/inv_798c58a7-ba85-4bfc-af26-fe287e763688

**Comment by TWJW-SANGER** [comment]
Resolved as part of GSU handover work.
Deprecated by the Product Owner.
