### ISSUE TITLE
DPL-048 Reject malfomed root sample ids to support important samples algorithm (C=?, V=4)

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#375]
**User story**
DPL-048 | As a picking algorithm specialist (Rhys M) I would like samples that have malformed root sample IDs to be rejected to avoid stopping the priority samples/'postcode picking' algorithm

**Who are the primary contacts for this story**
Rhys M (PAM)
Callum S (PAM)
Cristina A (PAM)

**Acceptance criteria**

To be considered successful the solution must allow:
- [ ] Understand current variation in root sample IDs that we had up to 1st July  (see post to slack 5th July at 11:45 (SQL) and 11:56 (list of samples, Cambridge look historical). Note some have brackets.
- [ ] Using that context, reject the concatenated root sample IDs observed from MK (example below)
- [ ] Patch the historical data (TBD Rich L in conversation with MK via Alan K)*
       *The malformed ids have been 'repaired'. Uncertain who/when. Patching will create duplicates (nts 30/7/21)

**Additional context**
From March 2020 the root sample IDs from the LH labs have been in the format: `ABC12345678`
From the beginning of July, MK expectantly uploaded plate maps with root sample IDs with concatenated plate id and well e.g.: `ABC12345678_RNA574294_A1`

Current validation is:

> Text. Can include hyphens and underscores but not spaces or other symbols. e.g. ‘ABC-1234_5678’.
>
> Full uniqueness for a sample row comes from the combination of 'Root Sample ID', 'RNA ID', 'Result' and 'Lab ID' column values. Duplicates of that combination are rejected.
>
> A blank value or a value of ‘Empty’ in this field will cause the row to be ignored.

Sparkes, A (2021) Lighthouse Plate Map Standard, pp.8

**Comment by rl15** [comment]
Alan K wrote (Tuesday, 6 July 2021 at 11:25)

Assumption is correct and yes truncate from the underscore as below.

This
AAI89074357_RNA574294_D1
 
To this
 
AAI89074357

**Comment by andrewsparkes** [comment]
Requirement says to reject, comment above from Alan says to truncate, needs clarification.
Suggest additional requirement: update Lighthouse Plate Map Standard document to make clearer what is expected, and what will happen if underscores are present (whether row is rejected or the field is going to be automatically truncated).

**Comment by neilsycamore** [comment]
Looking back over last six weeks, further variants of root_sample_ids containing underscores (all MK, no other LH)
plate_barcode, root_sample_id
RNA611623, LYS603241_C03
RNA611660, LYS603083_ACC_10536672
RNA606085, RNA606085_B12
RNA600119, LYS(561003)_ACC_10527793
RNA599531, LysisID_QNOS35748
RNA598599, LYSID_ACC_10527792

**Comment by pjvv** [comment]
From Alan (27/07/2021):

> Seems like you might not have picked a simple ticked to roll out on!
>
> We had assumed that it was a bug in UK Biocentre for a few weeks which was sorted at the time. Although in searching MLWH for the number of samples I would expect to be affected I can see we are still having occasional plates sent over with this issue.
>
> My query covering 01/06/21 – 25/07/21 shows 23,432 samples affected with most recent ones 24/07. I think I’ll need to go into this with the lighthouse themselves and sort at source before we do anything to our data. I’m surprised it hasn’t caused any issues in the system though.
>
> Thanks
> Alan

**Comment by rl15** [comment]
Email chain forwarded to rl15 on 2nd August Subject: FW: Root sample IDs, dated Tuesday, 27 July 2021 at 14:58 captures further detail between Philip and Eduardo & Alan K (PAM)

**Comment by TWJW-SANGER** [comment]
This has been resolved as part of the GSU handover work.
Deprecated by the Product Owner.
