### ISSUE TITLE
GPL-534 Rename samples collection after successful process

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#38]
**User story**
Currently samples collection are recreated every day from lighthouse files. The way it works, it could happen that during an error in process because of wrong inputs, all samples from a center might not be loaded, so we could end up with a smaller set of samples in database than what we had yesterday.

Currently we keep a copy for every day of all samples loaded. It would be a more consistent approach to not change the current samples collection unless we are confident on the consistency of data loaded. We could do this by not renaming the current samples collection unless all data load have happened without any critical errors.

**Who are the primary contacts for this story**
Eduardo Martin

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Use the current version of samples collection when new version load has failed with an error

**Dependencies**

**Additional context**
See problem from load on Jun 11th

**Comment by JamesGlover** [comment]
Got rename functions working, but working out how to approach tests and error detection.

The main function is currently quite hefty, and could do with refactoring. I've actually managed to get the test-suite to call it, and it seems to be using the files in the test directory in the absence of an ftp connection. Might actually be able to get a fairly decent integration test written with only minor refactoring.

**Comment by JamesGlover** [comment]
UAT indicates that this actually appears to work! Which means we've got a problem with one of the files.
