### ISSUE TITLE
DPL-181 Improve Crawler run performance to avoid manual intervention (C=S, V=5)

### ISSUE THREAD

**Issue by sdjmchattie** [sanger/crawler#418]
**Describe the Housekeeping**
At present, Crawler first downloads every file it can find on SFTP connections before it determines which ones it would like to process.  This means every run, hundreds if not thousands of files are downloaded and then thrown away as they were not needed / have been previously processed.

**Acceptance criteria**
- [ ] The time estimation for crawler should be only dependent on the number of new files received for this run.
- [ ] The time spent by crawler on checking the previous files should be under a fixed time always. We could establish a 5 minutes quota, for example. The increase on number of previous files in the sftp over time should not increase the running time over the quota established.

**Blocking issues**
None known.

**Additional context**
One possible fix for this problem is to use the SSH connection we already have to the server hosting the files so that we can run hashing algorithms on the server itself.  The hashes are much smaller than the files so we can selectively download only files we are interested in processing on this occasion.

Crawler is currently set to run every 30 minutes but takes as much as 20 minutes to run.  The hope is that this will bring run times down to only 2 or 3 minutes and that this will scale over time.

**Comment by stevieing** [comment]
hi, about the story of the sftp, the initial estimation was we received 160 files every day
2:22
we are currently receiving 320 files every day, they must have increased the number of files received

**Comment by emrojo** [comment]
sftp server openssh does not support check-file extension, https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-extensions-00#section-3 
we'll rollback to original plan of downloading recently updated files
