### ISSUE TITLE
DPL-nnn Decouple warehouse writes so migrations don't block the process

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#423]
**Describe the Housekeeping**
As a developer I would like to decouple writing the warehouse from crawler so the process can continue even when we are running warehouse migrations because that way we could do migrations during working hours without affecting the lab process.

**Blocking issues**
Describe any other issues or tickets that may be blocking this change.

**Additional context**

**Comment by stevieing** [comment]
This could be solved by the Heron OKR.

**Comment by emrojo** [comment]
This story won't be needed. At the moment crawler writes in the warehouse, so this problem can be solved during migrations without blocking lab work by stopping crawler, as it does not have to be running continuously, and restart again after finishing. After Heron OKR is done, there will be
