### ISSUE TITLE
DPL-203 - Think a way of disabling centres so we can change the source of a specific centres to read plate maps data from RabbitMQ instead of SFTP (S=M;C=M)

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#468]
**User story**
As a PSD developer I want to have a method that I can be use to enable/disable if a specific centre should read the data from SFTP files or from RabbitMQ. 

Suggestions: 
- it could be the centres table in Mongo that is created from the config files
- it could be commenting/removing the centre from the centres collection
- other options?

**Who are the primary contacts for this story**
Eduardo Martin
Andrew Sparkes

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] I can enable or disable specific centres to read either sftp or Rabbitmq so we can transition slowly by moving centres during transition phase 
- [ ] All code changes related Rabbitmq should not affect SFTP process functionality

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by sdjmchattie** [comment]
Trying to get an issue we saw in UAT fixed via pull request https://github.com/sanger/crawler/pull/523

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
