### ISSUE TITLE
DPL-198 - Feedback message JSON Schema (S=S; S=S)

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#473]
**User story**
As a PSD developer I want to define a JSON Schema for the feedback messages sent to the 'process_status' queue so we can share this definition with other groups about the status of the process of a message originally published in the 'samples_reception' queue. This message will be sent for both successfully processed messages and for errors so that PAM can understand which samples have been successfully received by PSD and which have not.

**Who are the primary contacts for this story**
Eduardo M
Andrew S
Stuart M
Jonnie B

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] A JSON schema must be defined to support the process_status message
- [x] Every message in the 'process_status' queue is a description of the status of the process from the sample message received in the 'sample_reception' queue
- [x] Every message must contain a message_id with the id of the original message that we are describing the status of process (should be defined in the message from the 'sample_reception' queue
- [x] Every message should have a status with values: 'OK' or 'ERR' indicating that the message_id referred has been correctly processed or not. 
- [x] Every message can contain a list of all errors found during the process of the sample
- [x] Every error described should have an error_type (as defined in confluence) and a human readable message, along with other information if is needed

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
