### ISSUE TITLE
DPL-253 Define all situations on updating samples from queue depending on the picking status

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#501]
**Description**

As PSD/PAM we want to have a document with the definition of all situations of updating fields in a sample because we want to have a clear view of the actions that can happen in each situation.

**Acceptance criteria**
- [x] Define the list of different situations that can happened
- [x] Create a table of all the different fields (rna_id, root_sample_id...) we can receive matching with every situation (not picked, already picked, already in SS...) what would be the result of the update (update success, not update and error, ...)
- [x] Only support update for fields: ```must_sequence``` and ```preferentially_sequence``` (before cherrypick)
- [x]  Agree this document between PSD/PAM

**Who the primary contacts are for this work**
Eduardo Martin
Andrew Sparkes

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by TWJW-SANGER** [comment]
We have agreed with GSU to limit the scope to updating the sample priority field.

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
