### ISSUE TITLE
DPL-343 - Archive backup files from centres not in use [C=S, V=4]

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#553]
**Describe the Housekeeping**
We currently don't receive anymore files from a group of centres that have closed. This task is to archive the backup files into a different storage as keeping it them in current volume is not going to be needed and is filling disk space. We currently only receive files for LSPA and QEUH.

The list of folders to archive in /var/lib/crawler/backups:

ALDP
BRBR
CAMC
HSL
MILK
NEWC
PLYM
RAND

**Blocking issues**
Describe any other issues or tickets that may be blocking this change.

**Additional context**

**Comment by emrojo** [comment]
In uat: ```ubuntu@dsm-01-uat:/var/lib/crawler/backups$ for file in `find . -name "*csv*"`; do sudo gzip $file; done```

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
