### ISSUE TITLE
GPL-568a Log LH plate maps data that fails to parse 

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#63]
**User story**
GPL-568 | As dev manager (Rich L) I want the Lighthouse plate map file names or root sample ids of data that fails to parse to be available in a human readable format to feedback to lighthouse via PAM

**Who are the primary contacts for this story**
Rich L

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] text output of LH plate map data that fails to parse available from URL, for a given date
- [ ] File fails due to unrecoverable error (e.g. no file header in first row or not csv extension)
- [ ] Individual sample fails due to unanticipated values (e.g. RNA plate barcode format)*1
- [ ] Divide output by lab 
- [ ] Date output

**Assumptions**
Log of failures can be run as asynchronous child of +ves on site report (Available here: https://psd.pages.internal.sanger.ac.uk/lighthouse_reports/)

**Mock up**
-----------------------------------
Date files parsed: 13/07/2020

Laboratory: Milton Keynes
plate map file MK_sanger_report_200527_0818.csv failed to parse due to no file header found 
plate map file AP_sanger_report_200527_0818.xls failed to parse due to unexpected file extension

sample <root sample id> failed to parse due to unexpected RNA plate id 
sample <root sample id> failed to parse due to unexpected RNA plate id 
...
sample <root sample id> failed to parse due to unexpected RNA plate id 

Laboratory: Cambridge-az
plate map file CB_sanger_report_200527_0818.xls failed to parse due to unexpected file extension

sample <root sample id> failed to parse due to unexpected RNA plate id 
...
sample <root sample id> failed to parse due to unexpected RNA plate id 

Laboratory: Alderney park
...

Laboratory: Glasgow
...

-----------------------------------

**Questions**
Q1. In this output *1 most errors appear to be a result of RNA plate barcode failing regex. What is impact of not checking RNA plate format (variation looks high), currently 9 variants known: https://ssg-confluence.internal.sanger.ac.uk/x/OpoKBg (see section 4.2.1 Variants of RNA plate barcode)

**Dependencies**
Not blocked but recommend doing first
- sanger/<repo>https://github.com/sanger/crawler/issues/62<issue_no.>

**Additional context**
*1 This is potentially a good starting point?: http://uat.lighthouse.psd.sanger.ac.uk/imports
Providing this manual record to PAM from 23/24th July: https://ssg-confluence.internal.sanger.ac.uk/x/OpoKBg

**Comment by harrietc52** [comment]
To `make-crawler-forgiving-epic`
> Added comments where validation can be improved,
> TODO - suss what error messages are to be added to Imports collection, errors list,
> TODO - make a UI to display errors nicely:
> possibly by adding a view to Lighthouse-UI, providing a centre and date,
> which will query the imports collection, and display errors in a table

**Comment by KatyTaylor** [comment]
![Screenshot 2020-07-30 at 16 51 22](https://user-images.githubusercontent.com/10407809/89021261-231cfe80-d318-11ea-8b74-0a1ab722fd07.png)
