### ISSUE TITLE
DPL-453 RVI: Check source plates and support test run week of 15th Aug

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/crawler#650]
**User story**
As Sara S I would like to run a new test plate for RVI. I have a supplied a list of source plate barcodes that need to be prepared to be picked, and I would like the picked samples moved into the RVI testing Study the same as for the previous test run.

**Who are the primary contacts for this story**
Sara S
Andrew S
Eduardo MR

**Who is the nominated tester for UAT**
If UAT is required it can be handled by PSD (test run the previously prepared script).

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] PSD check that chosen source plates have plate map data in PSD databases so they can be picked
- [x] PSD to do any work needed to make chosen source plates pickable - run script to generate UUIDs if needed
- [ ] physical picking of positives from the selected source plates into 4 x 96 destination LTHR Cherrypick plates
- [ ] manual intervention by Lab in LabWhere to move source plates from 'binned' location to freezer storage location
- [ ] manual intervention by PSD to change Study and names of the samples in these plates - Neil
- [ ] LTHR Cherrypick plates can then be quad stamped and run through the normal Heron Limber pipeline in Lab - inform Sara S once Ok for lab to continue

**Dependencies**
This story is blocked by the following dependencies:
- [ ] RVI team to create and inform PSD of Study to be used
- [x] RVI team to identify and inform PSD of set of source plate barcodes to be used
- [ ] RVI to agree with PSD the day of test (needs Neil availability for sample manual intervention)

References
NA

**Additional context**
See previous stories for test run of RVI here:
https://github.com/sanger/General-Backlog-Items/issues/194
https://github.com/sanger/General-Backlog-Items/issues/198
https://github.com/sanger/crawler/issues/600

**Comment by andrewsparkes** [comment]
List of plates from Alan K / Sara S:
Hi here’s a list of 97 plates, holding 396 samples. All from August and mainly from AP but some MK in there at the end.
 
 
AP-rna-00002109
AP-rna-00002234
AP-rna-00002240
AP-rna-00002302
AP-rna-00002353
AP-rna-00002477
AP-rna-00002484
AP-rna-00002500
AP-rna-00002542
AP-rna-00002665
AP-rna-00026650
AP-rna-00026701
AP-rna-00026759
AP-rna-00026882
AP-rna-00026927
AP-rna-00026959
AP-rna-00026975
AP-rna-00026984
AP-rna-00027006
AP-rna-00027075
AP-rna-00027158
AP-rna-00027170
AP-rna-00027235
AP-rna-00027268
AP-rna-00027269
AP-rna-00027272
AP-rna-00027275
AP-rna-00027280
AP-rna-00027281
AP-rna-00027299
AP-rna-00027305
AP-rna-00027311
AP-rna-00027324
AP-rna-00027330
AP-rna-00027353
AP-rna-00027362
AP-rna-00027369
AP-rna-00115844
AP-rna-00116189
AP-rna-00116491
AP-rna-00116597
AP-rna-00116834
AP-rna-00116858
AP-rna-00120102
AP-rna-00120129
AP-rna-00120130
AP-rna-00120131
AP-rna-00120144
AP-rna-00120146
AP-rna-00120159
AP-rna-00120285
AP-rna-00120307
AP-rna-00120350
AP-rna-00120364
AP-rna-00120391
AP-rna-00120414
AP-rna-00120500
AP-rna-00120567
AP-rna-00120580
AP-rna-00120586
AP-rna-00120637
AP-rna-00120649
AP-rna-00120679
AP-rna-00120768
AP-rna-00120860
AP-rna-00121020
AP-rna-00121111
AP-rna-00121187
AP-rna-00121206
AP-rna-00121271
AP-rna-00121351
AP-rna-00121365
AP-rna-00121369
AP-rna-00121371
AP-rna-00121398
AP-rna-00122970
AP-rna-00125061
AP-rna-00125078
AP-rna-00125081
AP-rna-00125094
AP-rna-00125122
AP-rna-00125164
AP-rna-00125185
AP-rna-00125347
AP-rna-00125381
AP-rna-00125469
AP-rna-00125657
AP-rna-00125667
AP-rna-00125713
AP-rna-00126630
RNA025398
RNA030447
RNA030458
RNA030493
RNA031445
RNA031884
RNA400713

**Comment by andrewsparkes** [comment]
total plates in list = 97

MLWH:
plates exist in lighthouse_sample = Yes all 97
samples in lighthouse_sample = 8990 (average around 93 per plate)
plates have uuids = 0
samples have uuids = 0

MongoDB:
plates exist in source_plates collection = No
plates exist in samples collection = Yes all 97
samples rows = 8990 (matches with MLWH count)
samples have lh_source_plate_uuids (query lh_source_plate_uuids:{$exists:true} ) = None all missing
samples have ls_sample_uuids (query llh_sample_uuid:{$exists:true} ) = None all missing

**Comment by andrewsparkes** [comment]
Script run successfully, finished 4.50 pm Monday 15th Aug
8890 samples updated

**Comment by SujitDey2022** [comment]
Related work is completed
