### ISSUE TITLE
GPL-577 Migrate to incremental update of LH plate map data 

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#66]
**User story**
GPL-577 | As dev team (all) we would like the LH crawler to incrementally add data from new file uploads rather than the current drop and reload strategy to ensure service availability for a time sensitive workflow if the SFTP data is compromised.

**Who are the primary contacts for this story**
Rich L

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] crawler identifies files with new timestamps on SFTP (not timestamp in file name)
- [ ] plate map data for each sample in new file(s) added to crawler persistence
- [ ] Any parsing errors logged (see GPL-568)
- [ ] Clarify and document how data in mongodb is backed up.
- [ ] Set up the timestamp for each sample of when it has been added to the system, as we won't have separate tables

**Assumptions**
No change in the feilds persisted with this change.
If new files containing previously seen root sample ids latest data overwrite historical values.

**Additional context**
Discussed in design meeting 17th July and document mail Rich L (Friday, 17 July 2020 at 13:59) Subject: Proposed changes to Lighthouse crawler + MLWH contents, mail to dev team

**Comment by harrietc52** [comment]
From Christina

Would it be feasible to have a column with the name of the plates we have the box manifest information but are not on the plate map? Does that make sense?

**Comment by harrietc52** [comment]
Merged in https://github.com/sanger/crawler/pull/93
