### ISSUE TITLE
GPL-444 new barcode prefix for  the Queen Elizabeth University Hospital (Glasgow): QEUH

### ISSUE THREAD

**Issue by rl15** [sanger/crawler#7]
**User story**
GPL-444 | As Liaison for lighthouse labs (Sonia G) I would like a new Barcode prefix for  the Queen Elizabeth University Hospital (Glasgow): QEUH to begin receiving plates via automatic process in May

**Who the primary contacts are for this story**
Sonia G
Rich C

**Acceptance criteria**
New barcode name space starting with QEUH  for plate maps put at SFTP - Glasgow share

**Additional context**
See email Livett, (Wednesday, 6 May 2020 at 15:35) Subject: Re: New lighthouse site: Queen Elizabeth University Hospital

**Comment by JamesGlover** [comment]
Added quick question fro Sonia G and Rich C

> Hello all,
> 
> I’ve added the configuration for Queen Elizabeth University Hospital import in the crawler. 
> 
> Can I just confirm that 'Queen Elizabeth University Hospital’ is an acceptable centre name to associated with QEUH in the crawler?
> 
> James

**Comment by JamesGlover** [comment]
Response

> Hi, 
> 
> I suggest we use UK Biocentre - Glasgow.
> Many thanks,
> 
> Best, Sonia

**Comment by JamesGlover** [comment]
> Sonia
> 
> I think that will confuse people, 
> 
> UK Biocentre Milton Keynes (Lab id MK)  - MILK COG-UK prefix
> Alderney Park (Lab id AP) - ALDP COG-UK prefix
> Glasgow (Lab id TBD waiting on their file) - QEUH COG-UK  prefix
> 
> 
> regards
> 
> Rich Livett (Core LIMS)

> All
> 
> Slacked with onia and agreement is
> 
>    UK Biocentre Milton Keynes (Lab id MK)  - MILK COG-UK prefix
>    Alderney Park (Lab id AP) - ALDP COG-UK prefix
>    Queen Elizabeth University Hospital (Lab id TBD waiting on their file) - QEUH COG-UK  prefix
> 
> As there is already a Glasgow consortium site.
> 
> regards
> 
> Rich Livett (Core LIMS)


> 'UK Biocentre Milton Keynes' is currently just 'UK Biocentre’ is there a desire to rename this? Will this include updating information which has already been imported.
> 
> James

> 
> James
> 
> No is fine leave as is.
> 
> regards
> 
> Rich Livett (Core LIMS)
