### ISSUE TITLE
DPL-639 Restrict values in the schema of priority flags to booleans (S=M, V=2)

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#726]
**Describe the story**
As a PSD developer I want to restrict the allowed values we can receive for priority flags to booleans, and not allow building a message with any other value (forbid integers, strings, etc) because crawler does not support handling booleans and any change in GSU could potentially create a valid message that wouldnt work when received in crawler, with the risk of not flagging priority samples from a (theoretically) "valid" message because of this problem.

Context: 
As part of RT769849 we have detected that the schema validates both 1 and true as true (valid flags). The problem is in our side we are not supporting this behaviour and currently we are receiving messages with flags set as '1' and updated it that way in the database, however, it is not correctly displayed in box buster, and it doesn't update the sample right in Dart.

**Acceptance criteria**
- [ ] The schemas are modified to support this change
- [ ] GSU uses the new version of the schema when agreed
- [ ] PSD uses the new version of the schema when agreed
- [ ] Any message that has a priority flag (must_sequence or preferentially_sequence) set to a value **different from** null (none), true or false should be rejected on serialization by Redpanda tools.
- [ ] Any message that has priority flags (must_sequence or preferentially_sequence) set to null, true or false should be processed correctly and the flags update the databases as normal.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by emrojo** [comment]
While testing in UAT found that the feedback message publishing was failing when it contained an error because now the library tries to be strict on all fields (fails with typeId not found):
```
2023-03-30 10:43:09,308 crawler.rabbit.messages.parsers.create_plate_message:167 ERROR   Error in create plate message: Sample with UUID....
Got an error: not_authed
Channel 1 was closed: Stream connection lost: ValueError('record contains more fields than the schema specifies: typeId')
Connection closed, reconnect necessary: Stream connection lost: ValueError('record contains more fields than the schema specifies: typeId')
```

Needs fixing before going to UAT testing by GSU

**Comment by SujitDey2022** [comment]
@emrojo @yoldas I was discussing this in the prioritisation meeting and it was suspected that the requirements mentioned in this story may have been handled in another user-story. Do let me know if this is yet to be handled or can be archived as a duplicate.

**Comment by yoldas** [comment]
@SujitDey2022 Which story you are referring to in your comment? I don't think this change is covered elsewhere.

**Comment by sdjmchattie** [comment]
The changes made to support this failed UAT before and haven't been worked on since.  I am removing them from the `develop` branch to avoid them going to production.  I've created a new branch and cherry picked the commits to it.  This can be found here in case this gets picked up again: https://github.com/sanger/lab-share-lib/tree/DPL-639-use-strict-validation-of-avro-schemas
