### ISSUE TITLE
DPL-931 Crawler to publish schemas on start

### ISSUE THREAD

**Issue by emrojo** [sanger/crawler#853]
**User story**
As PSD developer I want to automatize the method of deploying the Redpanda schemas so we minimize mistakes in deployment as forgetting to deploy a schema is a possible risk that could stop the process

**Who are the primary contacts for this story**
Eduardo Martin

**Who is the nominated tester for UAT**
PSD

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Before the application start, make sure that the schemas are updated in Redpanda
- [ ] If schemas are not up to date, update the schemas publishing the new version
- [ ] If there is any problem with this, fail and notify the users to sort it out

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by TWJW-SANGER** [comment]
Archiving as project Heron is now complete
